function generateAbout(){
  var nama = document.getElementById("nama").value;
  var url = document.getElementById("url").value;
  var owner = document.getElementById("owner").value;
  var deskripsi = document.getElementById("deskripsi").value;
  var email = document.getElementById("email").value;
var lang  = document.getElementById("about_language").value;

  let hasil = "";

  // =========================
  // BAHASA INDONESIA
  // =========================
  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

hasil = `
<h1>Tentang Kami</h1>

<p>Selamat datang di <strong>${nama}</strong>!</p>

<p>${nama} adalah sebuah platform yang menyediakan ${deskripsi}. Kami berkomitmen untuk memberikan layanan terbaik dan informasi yang bermanfaat bagi pengunjung kami.</p>

<p>Situs ini didirikan dan dikelola oleh <strong>${owner}</strong>. Kami terus berupaya mengembangkan ${nama} agar menjadi lebih baik dan memberikan pengalaman terbaik bagi pengguna.</p>

<h3>Misi Kami</h3>
<p>Misi kami adalah menyediakan konten yang berkualitas, terpercaya, dan mudah diakses oleh semua orang.</p>

<h3>Visi Kami</h3>
<p>Menjadi platform yang bermanfaat dan terpercaya di internet.</p>

<h3>Kontak Kami</h3>
<p>Jika Anda memiliki pertanyaan, saran, atau ingin bekerja sama, silakan hubungi kami melalui email di <a href="mailto:${email}">${email}</a>.</p>
<p>Website: <a href="${url}" target="_blank">${url}</a></p>
<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/about-us-online-generator.html" title="About Us Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiC56pdfbVWo4x06WnJwTjTxsWnqbaw2HSW2DNeE3Tru64n33aH0dF0N7ZyaYvnT_wqgYkQvXn7u0APrf14tTeEMtuxmqLMmrOJpuFGRoNO9XSm5VUu9oRjxm-BbOEcBSbErKrAGke5qRoaee-f1ivKad5weHPEU37gmoWC4-C8qg4xX1nS6ekjCnNYUk8N/s769/About%20Us%20Generator%20%28safelink-aza%29.png" alt="About Us Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our About Us, those changes will be posted here.</em><!-- END of About Us || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:100px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}
.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

hasil = `
<h1>About Us</h1>

<p>Welcome to <strong>${nama}</strong>!</p>

<p>${nama} is a platform that provides ${deskripsi}. We are committed to delivering the best services and useful information for our visitors.</p>

<p>This website was founded and managed by <strong>${owner}</strong>. We continuously strive to improve ${nama} to become better and provide the best experience for users.</p>

<h3>Our Mission</h3>
<p>Our mission is to provide high-quality, trustworthy, and easily accessible content for everyone.</p>

<h3>Our Vision</h3>
<p>To become a useful and trusted platform on the internet.</p>
<h3>Contact Us</h3>
<p>If you have any questions, suggestions, or would like to collaborate, please contact us via email at <a href="mailto:${email}">${email}</a>.</p>

<p>Website: <a href="${url}" target="_blank">${url}</a></p>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="About Us Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiC56pdfbVWo4x06WnJwTjTxsWnqbaw2HSW2DNeE3Tru64n33aH0dF0N7ZyaYvnT_wqgYkQvXn7u0APrf14tTeEMtuxmqLMmrOJpuFGRoNO9XSm5VUu9oRjxm-BbOEcBSbErKrAGke5qRoaee-f1ivKad5weHPEU37gmoWC4-C8qg4xX1nS6ekjCnNYUk8N/s769/About%20Us%20Generator%20%28safelink-aza%29.png" border="0" alt="Terms & Conditions Online Approved Site" /></a>
 <em>Should we update, amend or make any changes to our About Us, those changes will be posted here.</em><!-- END of About Us || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}
.credit-box img{
  width:240px;
  height:100px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilAbout").value = hasil;
}

function copyAbout(){
  var teks = document.getElementById("hasilAbout");
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}
// cont
function generateContactTool(){

  var nama    = document.getElementById("namaWeb").value;
  var alamat  = document.getElementById("alamat").value;
  var email   = document.getElementById("emailKontak").value;
  var wa      = document.getElementById("wa").value;
  var jam     = document.getElementById("jam").value;
  var lang    = document.getElementById("contact_language").value;

  let contact = "";

  // =========================
  // INDONESIA
  // =========================
  if(lang === "id"){

    contact = `
<h1>Hubungi Kami</h1>

<p>Jika Anda memiliki pertanyaan, saran, atau ingin bekerja sama dengan <strong>${nama}</strong>, silakan hubungi kami melalui informasi di bawah ini:</p>

<h3>Informasi Kontak</h3>

<ul>
  <li>Email: <a href="mailto:${email}">${email}</a></li>
  <li>WhatsApp: <a href="https://wa.me/${wa}" target="_blank">${wa}</a></li>
  <li>Alamat: ${alamat}</li>
  <li>Jam Operasional: ${jam}</li>
</ul>

<div class="contact-box">

<h3>Kirim Pesan</h3>

<input id="cnama" placeholder="Nama">
<input id="cemail" placeholder="Email">
<textarea id="cpesan" placeholder="Pesan"></textarea>
<button onclick="
window.location.href='mailto:${email}?subject=Pesan dari Website&body='+
'Nama: '+document.getElementById('cnama').value+
'%0AEmail: '+document.getElementById('cemail').value+
'%0A%0APesan:%0A'+
document.getElementById('cpesan').value
">
Kirim
</button>

</div>

<p>Kami akan merespons pesan Anda secepat mungkin. Terima kasih telah menghubungi kami.</p>

<style>
.contact-box{
  max-width:500px;
  margin:30px auto;
  padding:20px;
  border-radius:10px;
  background:#fff;
  box-shadow:0 5px 15px rgba(0,0,0,.1);
}

.contact-box input,
.contact-box textarea{
  width:100%;
  padding:10px;
  margin:10px 0;
  border:1px solid #ddd;
  border-radius:6px;
}
.contact-box button{
  width:100%;
  padding:12px;
  border:none;
  border-radius:6px;
  background:#f39c12;
  color:#fff;
  cursor:pointer;
}
</style>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="Contact Us Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEholgQamG9SFkW7jHVr62ShxRnoTbhl-KyNt0-9Uw3uc6DO3CodFdNIvJPdTeYWh8qb7AfDZwPk8bHPSxeRD_sNTgx2ohTEXlINXI4IozKlqiiIuL5aQUkoKmzsO2ddRzgPqPUOCMNecanwdjmMv0BUKOkVLVm47lTbpvrNythZ8mE2GiJN9f404JKdXYvw/s744/Contact%20Us%20Generator%20%28safelink-aza%29.png" alt="Contact Us Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Contact Us, those changes will be posted here.</em><!-- END of Contact Us || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}
.credit-box img{
  width:240px;
  height:120px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    contact = `
<h1>Contact Us</h1>

<p>If you have any questions, suggestions, or would like to collaborate with <strong>${nama}</strong>, please contact us using the information below:</p>

<h3>Contact Information</h3>

<ul>
  <li>Email: <a href="mailto:${email}">${email}</a></li>
  <li>WhatsApp: <a href="https://wa.me/${wa}" target="_blank">${wa}</a></li>
  <li>Address: ${alamat}</li>
  <li>Operating Hours: ${jam}</li>
</ul>

<div class="contact-box">
<h3>Send Message</h3>

<input id="cnama" placeholder="Your Name">
<input id="cemail" placeholder="Your Email">
<textarea id="cpesan" placeholder="Your Message"></textarea>

<button onclick="
window.location.href='mailto:${email}?subject=Message from Website&body='+
'Name: '+document.getElementById('cnama').value+
'%0AEmail: '+document.getElementById('cemail').value+
'%0A%0AMessage:%0A'+
document.getElementById('cpesan').value
">
Send
</button>

</div>

<p>We will respond to your message as soon as possible. Thank you for contacting us.</p>

<style>
.contact-box{
  max-width:500px;
  margin:30px auto;
  padding:20px;
  border-radius:10px;
  background:#fff;
  box-shadow:0 5px 15px rgba(0,0,0,.1);
}

.contact-box input,
.contact-box textarea{
  width:100%;
  padding:10px;
  margin:10px 0;
  border:1px solid #ddd;
  border-radius:6px;
}

.contact-box button{
  width:100%;
  padding:12px;
  border:none;
  border-radius:6px;
  background:#f39c12;
  color:#fff;
  cursor:pointer;
}
</style>
<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/contact-us-generator-online.html" title="Contact Us Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEholgQamG9SFkW7jHVr62ShxRnoTbhl-KyNt0-9Uw3uc6DO3CodFdNIvJPdTeYWh8qb7AfDZwPk8bHPSxeRD_sNTgx2ohTEXlINXI4IozKlqiiIuL5aQUkoKmzsO2ddRzgPqPUOCMNecanwdjmMv0BUKOkVLVm47lTbpvrNythZ8mE2GiJN9f404JKdXYvw/s744/Contact%20Us%20Generator%20%28safelink-aza%29.png" alt="Contact Us Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Contact Us, those changes will be posted here.</em><!-- END of Contact Us || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
  
}

.credit-box img{
  width:240px;
  height:120px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilContact").value = contact;
}

function copyContactTool(){

  var teks = document.getElementById("hasilContact");

  navigator.clipboard.writeText(teks.value);

  alert("Berhasil di copy!");
}

// pp
function generatePP(){
  var judul = document.getElementById("judul").value;
  var link = document.getElementById("link").value;
  var email = document.getElementById("email").value;

  
var lang  = document.getElementById("pp_language").value;

  let hasil = "";

  // =========================
  // BAHASA INDONESIA
  // =========================
  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

hasil = `
<h1>Kebijakan Privasi</h1>

<p>Kebijakan Privasi untuk ${judul}</p>

<p>Jika Anda memerlukan informasi lebih lanjut atau memiliki pertanyaan tentang kebijakan privasi kami, silakan hubungi kami melalui email di <a href="mailto:${email}">Privacy</a>.</p>

<p>Di ${link}, kami menganggap privasi pengunjung kami sangat penting. Dokumen kebijakan privasi ini menjelaskan secara rinci jenis informasi pribadi yang dikumpulkan dan dicatat oleh ${link} dan bagaimana kami menggunakannya.</p>

<h3>Berkas Log</h3>
<p>Seperti banyak situs web lainnya, ${link} menggunakan berkas log. Berkas-berkas ini hanya mencatat pengunjung situs - biasanya merupakan prosedur standar bagi perusahaan hosting dan bagian dari analitik layanan hosting. Informasi di dalam berkas log meliputi alamat protokol internet (IP), jenis browser, Penyedia Layanan Internet (ISP), cap tanggal/waktu, halaman rujukan/keluar, dan mungkin jumlah klik. Informasi ini digunakan untuk menganalisis tren, mengelola situs, melacak pergerakan pengguna di situs, dan mengumpulkan informasi demografis. Alamat IP, dan informasi serupa lainnya, tidak dihubungkan dengan informasi apa pun yang dapat diidentifikasi secara pribadi.</p>

<h3>Cookie dan Web Beacon</h3>
<p>${link} menggunakan cookie untuk menyimpan preferensi pengunjung dan menyesuaikan konten.</p>
<h3>Cookie DoubleClick DART</h3>
<li>&#8594; Google, sebagai vendor pihak ketiga, menggunakan cookie untuk menayangkan iklan di ${link}. Google menampilkan iklan berdasarkan kunjungan pengguna.</li>
<li>&#8594; Penggunaan cookie DART oleh Google memungkinkan Google untuk menayangkan iklan kepada pengunjung situs kami berdasarkan kunjungan mereka ke ${link} dan situs lain di Internet.</li>
<li>&#8594; Pengguna dapat menolak penggunaan cookie DART dengan mengunjungi kebijakan privasi jaringan iklan dan konten Google di URL berikut - <a href="https://policies.google.com/technologies/ads" target="_blank">https://policies.google.com/technologies/ads</a></li>

<h3>Mitra Periklanan</h3>
<p>Beberapa mitra periklanan kami mungkin menggunakan cookie dan web beacon di situs kami. Mitra periklanan kami meliputi .......

<li>Google</li>
<li>Adsterra</li>
<li>Monetag</li>
<li>Amazon</li>
<li>Widget Bucks</li>
<li>Adbrite</li>
<li>Clickbank</li>
<li>Linkshare</li>
<li>Jaringan Penerbit Yahoo!</li>
<li>Azoogle</li>
<li>Chitika</li>
<li>Kontera</li>
<li>Lainnya</li>
<p>
Meskipun masing-masing mitra periklanan ini memiliki Kebijakan Privasi sendiri untuk situs mereka, sumber daya yang diperbarui dan terhubung melalui tautan tersedia di sini: <a href="https://safelink-aza.blogspot.com/2026/04/privacy-policy-online-generator.html" target="_blank">Kebijakan Privasi</a> .</p>
<p>
Anda dapat melihat daftar ini untuk menemukan kebijakan privasi untuk setiap mitra periklanan ${link}.
</p>
<p>
Server iklan pihak ketiga atau jaringan iklan ini menggunakan teknologi dalam iklan dan tautan masing-masing yang muncul di ${link}  dan yang dikirim langsung ke browser Anda. Mereka secara otomatis menerima alamat IP Anda ketika ini terjadi. Teknologi lain (seperti cookie, JavaScript, atau Web Beacon) juga dapat digunakan oleh jaringan iklan pihak ketiga situs kami untuk mengukur efektivitas kampanye iklan mereka dan/atau untuk mempersonalisasi konten iklan yang Anda lihat di situs.</p>

<h3>Kebijakan Privasi Pihak Ketiga</h3>
<p>Kami tidak memiliki kontrol atas cookie pihak ketiga. ${link} tidak memiliki akses atau kendali atas cookie yang digunakan oleh pengiklan pihak ketiga.</p>

<p>Jika Anda ingin menonaktifkan cookie, Anda dapat melakukannya melalui opsi peramban Anda masing-masing. Informasi lebih detail tentang pengelolaan cookie dengan peramban web tertentu dapat ditemukan di situs web masing-masing peramban. <a href="https://www.google.com/search?q=apa+itu+cookie&oq=apa+itu+cokie?" target="_blank">Apa Itu Cookie?</a></p>

<h3>Informasi Anak-Anak</h3>
<p>Kami percaya penting untuk memberikan perlindungan tambahan bagi anak-anak secara daring. Kami mendorong orang tua dan wali untuk meluangkan waktu bersama anak-anak mereka secara daring untuk mengamati, berpartisipasi, dan/atau memantau serta membimbing aktivitas daring mereka. </p>
<p>${link} tidak secara sengaja mengumpulkan informasi identitas pribadi apa pun dari anak-anak di bawah usia 13 tahun. Jika orang tua atau wali yakin bahwa situs kami memiliki informasi identitas pribadi anak di bawah usia 13 tahun dalam basis datanya, harap segera hubungi kami (menggunakan kontak di paragraf pertama) dan kami akan melakukan upaya terbaik untuk segera menghapus informasi tersebut dari catatan kami.</p>

<h3>Kebijakan Privasi Online Saja</h3>
<p>Berlaku hanya untuk aktivitas online.</p>

<h3>Persetujuan</h3>
<p>Dengan menggunakan situs ini, Anda menyetujui kebijakan ini.</p>

<h3>Pembaruan</h3>
<p>Kebijakan ini terakhir diperbarui pada: Sabtu, 9 Mei 2026 . Jika kami <a href="" target="_self">memperbarui, mengubah, atau melakukan perubahan apa pun pada kebijakan privasi kami</a>, perubahan tersebut akan diposting di sini.</p>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="Privacy Policy Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxPRZ7KL7-Z4LVXd6kjUmLSPT57oX8npQ4VJ4uo1EXb-45VnOYh3G833L47YyQMkCQtDsKytGXTICuP0w2izij9hxXeApWnrQQmlo0uqE-ym4UYIcDN5_-5mqPxo64kwDAmQyWgBjgNZRNUnEwOyj33R7Tyu5TnwqQUuCNa2XJBzIOp6cOySYTTObz7GsZ/s1254/Privacy%20Policy%20Generator%20%28safelink-aza%29.png" alt="Privacy Policy Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Privacy Policy, those changes will be posted here.</em><!-- END of Privacy Policy || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:80px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}
.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

hasil = `
<h1>Privacy Policy</h1>

<p>Privacy Policy for ${judul}</p>

<p>If you require any more information or have any questions about our privacy policy, please feel free to contact us by email at <a href="mailto:${email}">Privacy</a>.</p>

<p>At ${link}, we consider the privacy of our visitors to be extremely important. This privacy policy document describes in detail the types of personal information collected and recorded by ${link} and how we use it.</p>

<h3>Log Files</h3>
<p>Like many other websites, ${link} uses log files. These files merely log visitors to the site - usually a standard procedure for hosting companies and part of hosting services analytics. The information inside the log files includes internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date/time stamp, referring/exit pages, and possibly the number of clicks. This information is used to analyze trends, administer the site, track user movement around the site, and gather demographic information. IP addresses and other such information are not linked to any information that is personally identifiable.</p>

<h3>Cookies and Web Beacons</h3>
<p>${link} uses cookies to store visitors' preferences and customize content.</p>

<h3>DoubleClick DART Cookie</h3>
<li>&#8594; Google, as a third-party vendor, uses cookies to serve ads on ${link}. Google serves ads based on 
user visits.</li>
<li>&#8594; Google's use of the DART cookie enables it to serve ads to our site's visitors based upon their visit to ${link} and other sites on the Internet.</li>
<li>&#8594; Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy at the following URL - <a href="https://policies.google.com/technologies/ads" target="_blank">https://policies.google.com/technologies/ads</a></li>

<h3>Advertising Partners</h3>
<p>Some of our advertising partners may use cookies and web beacons on our site. Our advertising partners include .......

<li>Google</li>
<li>Adsterra</li>
<li>Monetag</li>
<li>Amazon</li>
<li>Widget Bucks</li>
<li>Adbrite</li>
<li>Clickbank</li>
<li>Linkshare</li>
<li>Yahoo! Publisher Network</li>
<li>Azoogle</li>
<li>Chitika</li>
<li>Kontera</li>
<li>Others</li>
<p>
While each of these advertising partners has their own Privacy Policy for their site, an updated and linked resource is maintained here: <a href="https://safelink-aza.blogspot.com/2026/04/privacy-policy-online-generator.html" target="_blank">Privacy Policies</a> .</p>
<p>
You may consult this listing to find the privacy policy for each of the advertising partners of ${link}.
</p>

<p>
These third-party ad servers or ad networks use technology in their respective advertisements and links that appear on ${link} and which are sent directly to your browser. They automatically receive your IP address when this occurs. Other technologies (such as cookies, JavaScript, or Web Beacons) may also be used by our site's third-party ad networks to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on the site.</p>

<h3>Third Party Privacy Policies</h3>
<p>We have no access to or control over third-party cookies. ${link} has no access to or control over these cookies that are used by third-party advertisers
.</p>

<p>If you wish to disable cookies, you may do so through your individual browser options. More detailed information about cookie management with specific web browsers can be found at the browsers' respective websites. <a href="https://www.google.com/search?q=what+is+cookie?" target="_blank">What Are Cookies?</a></p>

<h3>Children's Information</h3>
<p>We believe it is important to provide added protection for children online. We encourage parents and guardians to spend time online with their children to observe, participate in, and/or monitor and guide their online activity. </p>
<p>${link} does not knowingly collect any personally identifiable information from children under the age of 13. If a parent or guardian believes that our site has personally identifiable information of a child under the age of 13 in its database, please contact us immediately (using the contact information in the first paragraph) and we will use our best efforts to promptly remove such information from our records.</p>

<h3>Online Privacy Policy Only</h3>
<p>Applicable only to online activities.</p>

<h3>Consent</h3>
<p>By using this site, you consent to this policy.</p>

<h3>Updates</h3>
<p>This policy was last updated on: Saturday, May 9, 2026 .
<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/privacy-policy-online-generator.html" title="Privacy Policy Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgxPRZ7KL7-Z4LVXd6kjUmLSPT57oX8npQ4VJ4uo1EXb-45VnOYh3G833L47YyQMkCQtDsKytGXTICuP0w2izij9hxXeApWnrQQmlo0uqE-ym4UYIcDN5_-5mqPxo64kwDAmQyWgBjgNZRNUnEwOyj33R7Tyu5TnwqQUuCNa2XJBzIOp6cOySYTTObz7GsZ/s1254/Privacy%20Policy%20Generator%20%28safelink-aza%29.png" alt="Privacy Policy Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Privacy Policy, those changes will be posted here.</em><!-- END of Privacy Policy || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:80px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasil").value = hasil;
}

function copyPP(){
  var teks = document.getElementById("hasil");
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}