function generateDmca(){

  var nama  = document.getElementById("dmca_siteName").value;
  var url   = document.getElementById("dmca_siteUrl").value;
  var email = document.getElementById("dmca_siteEmail").value;
  var lang  = document.getElementById("dmca_language").value;

  let dmca = "";

  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

dmca = `
<div class="legal-page">
  <h1>DMCA Policy</h1>
  <p>Di perbaharui pada: <strong>${tanggal}</strong></p>

  <p>
    Website ini (<strong>${nama}</strong>) menghormati hak kekayaan intelektual orang lain dan mematuhi ketentuan
    <em>Digital Millennium Copyright Act (DMCA)</em>.
  </p>

  <h2>1. Hak Cipta</h2>
  <p>
    Semua konten yang ditampilkan di situs ini dibuat untuk tujuan informasi, edukasi, dan referensi.
    Kami tidak bermaksud melanggar hak cipta pihak mana pun.
  </p>

  <h2>2. Laporan Pelanggaran</h2>
  <p>
    Jika Anda adalah pemilik hak cipta dan menemukan konten yang melanggar di situs ini,
    silakan hubungi kami dengan informasi berikut:
  </p>

  <ul>
    <li>Bukti kepemilikan konten</li>
    <li>URL konten yang dilanggar (<b>Contoh</b>: <em>${url}/2026/12/konten-hak-cipta.html</em></li>
    <li>Kontak email Anda</li>
  </ul>

  <h2>3. Tindakan Kami</h2>
  <p>
    Kami akan segera meninjau laporan Anda dan menghapus konten yang terbukti melanggar hak cipta
    dalam waktu yang wajar.
  </p>

  <h2>4. Kontak DMCA</h2>
  <p>Email: <strong>${email}</strong></p>
  <p>Halaman Kontak: <a href="${url}/p/contact.html" target="_blank">${url}/p/contact.html</a>
</div>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="DMCA Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEidAHSfQuQsoDRzriXtZUY-vmYG-bYF9a8duFPf8-ZYSO4bToZe75hQLcZgpSFRHjq6409lXgjH7jz2sVSCZQCRfJvrFo_8U3TuO2nLEr1Wrbo7N2XFViRM8fQoiP_Yy3QtGxdWu0kxHiye8Zr8GejFQxs-BsUmXVkqMxVIPi3REr4pFhOOrB41vftXhair/s1536/DMCA%20Generator%28safelink-aza%29.png" alt="DMCA Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our DMCA Policy, those changes will be posted here.</em><!-- END of DMCA || Generated by https://safelink-aza.blogspot.com || --></div>
 <style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:80px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

dmca = `
<h1>DMCA Policy</h1>

  <p>Last updated: <strong>${tanggal}</strong></p>

  <p>
    This website (<strong>${nama}</strong>) respects the intellectual property rights of others and complies with the
    provisions of the <em>Digital Millennium Copyright Act (DMCA)</em>.
  </p>

  <h2>1. Copyright</h2>
  <p>
    All content displayed on this website is created for informational, educational, and reference purposes.
    We do not intend to infringe any copyrighted material belonging to any party.
  </p>

  <h2>2. Copyright Infringement Report</h2>
  <p>
    If you are a copyright owner and believe that any content on this website infringes your rights,
    please contact us with the following information:
  </p>

  <ul>
    <li>Proof of ownership of the content</li>
    <li>URL of the infringing content (<b>Example</b>: <em>${url}/2026/12/content-copyright.html</em></li>
    <li>Your contact email address</li>
  </ul>

  <h2>3. Our Actions</h2>
  <p>
    We will promptly review your complaint and remove any content proven to violate copyright
    within a reasonable time frame.
  </p>

  <h2>4. DMCA Contact</h2>
  <p>Email: <strong>${email}</strong></p>
  <p>Contact Page: <a href="${url}/p/contact.html" target="_blank">${url}/p/contact.html</a>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/2026/05/dmca-policy-generator.html" title="DMCA Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEidAHSfQuQsoDRzriXtZUY-vmYG-bYF9a8duFPf8-ZYSO4bToZe75hQLcZgpSFRHjq6409lXgjH7jz2sVSCZQCRfJvrFo_8U3TuO2nLEr1Wrbo7N2XFViRM8fQoiP_Yy3QtGxdWu0kxHiye8Zr8GejFQxs-BsUmXVkqMxVIPi3REr4pFhOOrB41vftXhair/s1536/DMCA%20Generator%28safelink-aza%29.png" alt="DMCA Online Approved Site" /></a>
 <em>Should we update, amend or make any changes to our DMCA Policy, those changes will be posted here.</em><!-- END of DMCA || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}
.credit-box img{
  width:240px;
  height:80px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilDmca").value = dmca;
}

function copyText(id){
  var teks = document.getElementById(id);
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}