function generateDisclaimer(){

  var nama = document.getElementById("d_siteName").value;
  var url  = document.getElementById("d_siteUrl").value;
  var lang = document.getElementById("language").value;

  let disclaimer = "";

  // =========================
  // INDONESIA
  // =========================
  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

disclaimer = `

<h1>Disclaimer untuk ${nama}</h1>

<p>Semua informasi di situs web ini - ${url} - dipublikasikan dengan itikad baik dan hanya untuk tujuan informasi umum. ${nama} tidak memberikan jaminan apa pun tentang kelengkapan, keandalan, dan keakuratan informasi ini.</p>

<p>Segala tindakan yang Anda lakukan atas informasi yang Anda temukan di situs ini sepenuhnya merupakan risiko Anda sendiri. ${nama} tidak akan bertanggung jawab atas kerugian dan/atau kerusakan sehubungan dengan penggunaan situs kami.</p>

<p>Dari situs kami, Anda dapat mengunjungi situs lain melalui tautan. Kami tidak memiliki kontrol atas konten situs tersebut.</p>

<p>Persetujuan: Dengan menggunakan situs kami, Anda menyetujui disclaimer ini.</p>

<p>Pembaruan: ${tanggal}</p>


<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/disclaimer-terms-conditions-online.html" title="Disclaimer Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgKVZp2HqvCISALHei7LzHM_0sQdNc-WrAGnRvK6cZCUYwGIIntnCAjEZybmh7ov4OsXbiYBnCHvauT1kdPRIt89ixlsy8x3M9W1yyLB8LWgbBVd59r7ffx2r4L3pe9kH30xKX4qw6VHgH6o2pMlsxGlgT_9XpTIfJojnjPl4-tId1FvKcV-O3mtjbgwTXA/s1505/Disclaimer%20Online%20Generator%20%28safelink-aza%29.png" alt="Disclaimer Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Disclaimer, those changes will be posted here.</em><!-- END of Disclaimer || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}
.credit-box img{
  width:240px;
  height:105px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

disclaimer = `
<h1>Disclaimer for ${nama}</h1>

<p>All information on this website - ${url} - is published in good faith and for general informational purposes only. ${nama} makes no warranties regarding the completeness, reliability, and accuracy of this information.</p>

<p>Any action you take based on the information you find on this website is strictly at your own risk. ${nama} will not be liable for any losses and/or damages in connection with the use of our website.</p>

<p>From our website, you may visit other websites through external links. We have no control over the content of those sites.</p>

<p>Consent: By using our website, you hereby consent to this disclaimer.</p>

<p>Update: ${tanggal}</p>
<hr>
<div class="credit-box">
 <a href="https://safelink-aza.blogspot.com/2026/04/disclaimer-terms-conditions-online.html" title="Disclaimer Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgKVZp2HqvCISALHei7LzHM_0sQdNc-WrAGnRvK6cZCUYwGIIntnCAjEZybmh7ov4OsXbiYBnCHvauT1kdPRIt89ixlsy8x3M9W1yyLB8LWgbBVd59r7ffx2r4L3pe9kH30xKX4qw6VHgH6o2pMlsxGlgT_9XpTIfJojnjPl4-tId1FvKcV-O3mtjbgwTXA/s1505/Disclaimer%20Online%20Generator%20%28safelink-aza%29.png" alt="Disclaimer Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Disclaimer, those changes will be posted here.</em><!-- END of Disclaimer || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:105px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilDisclaimer").value = disclaimer;
}

function copyText(id){
  var teks = document.getElementById(id);
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}

// terms
function generateTerms(){

  var nama  = document.getElementById("t_siteName").value;
  var url   = document.getElementById("t_siteUrl").value;
  var email = document.getElementById("t_siteEmail").value;
  var lang  = document.getElementById("terms_language").value;

  let terms = "";

  // =========================
  // BAHASA INDONESIA
  // =========================
  if(lang === "id"){

    var tanggal = new Date().toLocaleDateString("id-ID", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

terms = `

<h1>Syarat & Ketentuan ${nama}</h1>

  <p>Selamat datang di situs <strong>${nama}</strong>.</p>

  <p>
    Syarat dan ketentuan ini menjelaskan aturan serta ketentuan penggunaan
    situs web yang beralamat di <strong>${url}</strong>.
  </p>

  <p>
    Dengan mengakses situs web ini, Anda dianggap telah memahami dan menyetujui
    seluruh syarat dan ketentuan yang berlaku. Jika Anda tidak menyetujui salah
    satu bagian dari syarat dan ketentuan ini, mohon untuk tidak melanjutkan
    penggunaan situs web ini.
  </p>

  <h3>Definisi</h3>

  <p>
    Dalam dokumen ini, istilah &#8220;Klien&#8221;, &#8220;Anda&#8221;, dan &#8220;Pengguna&#8221; merujuk kepada
    pihak yang mengakses situs web ini. Istilah &#8220;Kami&#8221;, &#8220;Kita&#8221;, dan
    &#8220;Perusahaan&#8221; merujuk kepada pengelola situs web ini. Sedangkan istilah
    &#8220;Pihak&#8221; mengacu kepada pengguna dan pengelola situs secara bersama-sama.
  </p>

  <h3>Cookie</h3>

  <p>
    Situs web ini menggunakan cookie untuk meningkatkan pengalaman pengguna.
    Dengan mengakses situs ini, Anda menyetujui penggunaan cookie sesuai dengan
    Kebijakan Privasi yang berlaku.
  </p>

  <p>
    Cookie digunakan untuk mengaktifkan fitur tertentu dan membantu kami
    memahami aktivitas pengguna di situs web. Beberapa mitra periklanan atau
    afiliasi kami juga dapat menggunakan cookie.
  </p>

  <h3>Lisensi</h3>

  <p>
    Kecuali dinyatakan lain, seluruh hak kekayaan intelektual atas materi yang
    terdapat di situs <strong>${url}</strong> dimiliki oleh kami dan/atau
    pemberi lisensi kami. Semua hak dilindungi oleh undang-undang yang berlaku.
  </p>

  <p>Anda diperbolehkan mengakses situs ini untuk penggunaan pribadi dengan ketentuan berikut:</p>

  <ul>
    <li>Dilarang mempublikasikan ulang materi dari situs ini.</li>
    <li>Dilarang menjual, menyewakan, atau memberikan sub-lisensi materi situs.</li>
    <li>Dilarang menyalin atau menggandakan konten situs tanpa izin.</li>
    <li>Dilarang mendistribusikan ulang konten dari situs ini.</li>
  </ul>

  <h3>Komentar Pengguna</h3>

  <p>
    Beberapa bagian situs ini memungkinkan pengguna untuk memposting komentar
    dan bertukar informasi. Kami tidak menyaring, mengedit, atau meninjau
    komentar sebelum ditampilkan di situs web.
  </p>

  <p>
    Komentar yang dipublikasikan sepenuhnya merupakan tanggung jawab masing-masing
    pengguna dan tidak mencerminkan pandangan kami.
  </p>

  <p>Dengan memposting komentar, Anda menyatakan bahwa:</p>

  <ul>
    <li>Anda memiliki hak untuk mempublikasikan komentar tersebut.</li>
    <li>Komentar tidak melanggar hak cipta, merek dagang, atau hak pihak lain.</li>
    <li>Komentar tidak mengandung unsur fitnah, pornografi, atau tindakan melanggar hukum.</li>
    <li>Komentar tidak digunakan untuk spam atau promosi ilegal.</li>
  </ul>

  <p>
    Kami berhak menghapus komentar yang dianggap tidak pantas atau melanggar
    syarat dan ketentuan ini.
  </p>

  <h3>Tautan ke Situs Kami</h3>

  <p>
    Organisasi tertentu seperti instansi pemerintah, mesin pencari, media
    berita, dan direktori online diperbolehkan menautkan ke situs kami tanpa
    izin tertulis sebelumnya.
  </p>

  <p>
    Kami juga dapat mempertimbangkan permintaan tautan dari organisasi lain
    apabila dinilai sesuai dan tidak merugikan pihak mana pun.
  </p>

  <h3>iFrame</h3>

  <p>
    Tanpa izin tertulis dari kami, Anda tidak diperbolehkan membuat frame atau
    tampilan lain yang mengubah visual situs web kami.
  </p>

  <h3>Tanggung Jawab Konten</h3>

  <p>
    Kami tidak bertanggung jawab atas konten yang muncul di situs web pihak
    ketiga yang menautkan ke situs kami. Anda setuju untuk melindungi kami dari
    segala klaim yang timbul akibat konten di situs Anda.
  </p>

  <h3>Reservasi Hak</h3>

  <p>
    Kami berhak meminta penghapusan tautan ke situs kami kapan saja. Kami juga
    berhak mengubah syarat dan ketentuan ini sewaktu-waktu tanpa pemberitahuan
    sebelumnya.
  </p>

  <h3>Penghapusan Tautan</h3>

  <p>
    Jika Anda menemukan tautan di situs kami yang dianggap tidak pantas, Anda
    dapat menghubungi kami. Kami akan mempertimbangkan permintaan tersebut,
    namun tidak berkewajiban untuk menghapusnya.
  </p>

  <h3>Penafian</h3>

  <p>
    Kami tidak menjamin bahwa seluruh informasi di situs ini selalu akurat,
    lengkap, atau terbaru. Semua layanan dan informasi disediakan &#8220;sebagaimana
    adanya&#8221;.
  </p>

  <p>
    Sejauh diizinkan oleh hukum yang berlaku, kami tidak bertanggung jawab atas
    kerugian atau kerusakan apa pun yang timbul akibat penggunaan situs web ini.
  </p>

  <p>
    Selama situs web ini tersedia secara gratis, kami tidak bertanggung jawab
    atas kehilangan data, gangguan layanan, atau kerusakan lainnya yang mungkin
    terjadi akibat penggunaan situs ini.
  </p>

<h3>Kontak</h3>
<p>Email: ${email}</p>

<p>Terakhir diperbarui: ${tanggal}</p>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/2026/04/terms-conditions-online-generator.html" title="Terms & Conditions Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgscU8KF9hECAtS54LLsRQFQCweDLwFcG1zT5SmTIUTurZSpJRicb7qsJY5MHkIEAqNCEALyHDYOkh3epd69wOotup6kGm9hgQqt4FFEYQv0zIv4FTjjsU_7D7nX1isMDMxydnB08Cwie0CRMTG8RPA80Sg8Z0Gxjxvug4b_urBk4Y_WauOJZmoq4QSR6Ya/s1505/Terms%20&%20Conditions%20Online%20Generator%20%28safelink-aza%29.png" alt="Terms & Conditions Online Approved Site"/></a>
 <em>Should we update, amend or make any changes to our Terms & Conditions, those changes will be posted here.</em><!-- END of Terms & Conditions || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:120px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  // =========================
  // ENGLISH
  // =========================
  else{

    var tanggal = new Date().toLocaleDateString("en-US", {
      day:'numeric',
      month:'long',
      year:'numeric'
    });

terms = `

<h1>Terms & Conditions ${nama}</h1>

<p>Welcome to <strong>${nama}</strong>!</p><br/>

<p>These terms and conditions outline the rules and regulations for the use of <strong>this web</strong>'s Website, located at <strong>${url}</strong></p><br/>

<p>By accessing this website we assume you accept these terms and conditions. Do not continue to use <strong>this web</strong> if you do not agree to take all of the terms and conditions stated on this page.</p><br/>

<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company&#8217;s terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client&#8217;s needs in respect of provision of the Company&#8217;s stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p><br/>

<h3><strong>Cookies</strong></h3>

<p>We employ the use of cookies. By accessing <strong>this web</strong>, you agreed to use cookies in agreement with the <strong>this web</strong>'s Privacy Policy.</p><br/>

<p>Most interactive websites use cookies to let us retrieve the user&#8217;s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p><br/>

<h3><strong>License</strong></h3>

<p>Unless otherwise stated, <strong>this web</strong> and/or its licensors own the intellectual property rights for all material on <strong>this web</strong>. All intellectual property rights are reserved. You may access this from <strong>this web</strong> for your own personal use subjected to restrictions set in these terms and conditions.</p><br/>

<p>You must not:</p><br/>

<ul>

	<li>Republish material from <strong>this web</strong></li>

	<li>Sell, rent or sub-license material from <strong>this web</strong></li>

	<li>Reproduce, duplicate or copy material from <strong>this web</strong></li>

	<li>Redistribute content from <strong>this web</strong></li>

</ul>

<p>This Agreement shall begin on the date hereof.</p><br/>

<p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. <strong>this web</strong> does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of <strong>this web</strong>,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, <strong>this web</strong> shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p><br/>

<p><strong>this web</strong> reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</p><br/>

<p>You warrant and represent that:</p><br/>

<ul>

	<li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>

	<li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>

	<li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>

	<li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>

</ul>

<p>You hereby grant <strong>this web</strong> a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p><br/>

<h3><strong>Hyperlinking to our Content</strong></h3>

<p>The following organizations may link to our Website without prior written approval:</p><br/>

<ul>

	<li>Government agencies;</li>

	<li>Search engines;</li>

	<li>News organizations;</li>

	<li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>

	<li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</li>

</ul>

<p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party&#8217;s site.</p><br/>

<p>We may consider and approve other link requests from the following types of organizations:</p><br/>

<ul>

	<li>commonly-known consumer and/or business information sources;</li>

	<li>dot.com community sites;</li>

	<li>associations or other groups representing charities;</li>

	<li>online directory distributors;</li>

	<li>internet portals;</li>

	<li>accounting, law and consulting firms; and</li>

	<li>educational institutions and trade associations.</li>

</ul>

<p>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of <strong>this web</strong>; and (d) the link is in the context of general resource information.</p><br/>

<p>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party&#8217;s site.</p><br/>

<p>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to <strong>this web</strong>. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</p><br/>

<p>Approved organizations may hyperlink to our Website as follows:</p><br/>

<ul>

	<li>By use of our corporate name; or</li>

	<li>By use of the uniform resource locator being linked to; or</li>

	<li>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party&#8217;s site.</li>

</ul>

<p>No use of <strong>this web</strong>'s logo or other artwork will be allowed for linking absent a trademark license agreement.</p><br/>

<h3><strong>iFrames</strong></h3>

<p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p><br/>

<h3><strong>Content Liability</strong></h3>

<p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p><br/>

<h3><strong>Reservation of Rights</strong></h3>

<p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it&#8217;s linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p><br/>

<h3><strong>Removal of links from our website</strong></h3>

<p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</p><br/>

<p>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p><br/>

<h3><strong>Disclaimer</strong></h3>

<p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p><br/>

<ul>

	<li>limit or exclude our or your liability for death or personal injury;</li>

	<li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>

	<li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>

	<li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>

</ul>

<p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</p><br/>

<p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>

<h3>Contact</h3>
<p>Email: ${email}</p>

<p>Last updated: ${tanggal}</p>
<hr>
<div class="credit-box">
 <a href="https://bloggertool-html.blogspot.com/p/tool.html" title="Terms & Conditions Online Generator Approved Site" target="_blank"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi-CiapLCqwcPwt4LQnBvO-W1tSXSMmIkQl5e-axQltZDhCz_owIFgCtv5sS1fm7c3WvveANEs2IDm2j7mFkiomKeMKx7Jftez7zARJ8-eAzBO6x4wc-EDolw8Hsm6BGhBAH2yLqLCofnKkDF6C7GZ4lYfox3nPNSiufcgbhc-gvyqWRZlauoF4l67V-EFS/s1024/Terms%20&%20Conditions%20Generator%20%28Safelink-aza%29.png" alt="Terms & Conditions Online Approved Site" /></a>
 <em>Should we update, amend or make any changes to our Terms & Conditions, those changes will be posted here.</em><!-- END of Terms & Conditions || Generated by https://safelink-aza.blogspot.com || --></div>

<style>
.credit-box{
  display:flex;
  align-items:center;
  gap:15px;
}

.credit-box img{
  width:240px;
  height:120px;
  object-fit:cover;
  border-radius:10px;
  display:block;
}

.credit-box em{
  font-size:14px;
  line-height:1.6;
}
</style>
`;

  }

  document.getElementById("hasilTerms").value = terms;
}

function copyText(id){
  var teks = document.getElementById(id);
  teks.select();
  document.execCommand("copy");
  alert("Berhasil di copy!");
}


